fix(scripts): fix qpc container execution on podman with Linux
Podman on Linux requires the :z suffix in volume option in order
to allow proper mounting permission (due to SELinux restrictions).

The actual message without :z option is:

podman run --rm -p 5000:8000 \
	-v /home/user/src/quipucords-ui/.qpc/quipucords/docs/swagger.yml:/data/swagger.yaml \
	--name qpc-dev docker.io/palo/swagger-api-mock

Fatal error: Error opening file "/data/swagger.yaml"
EACCES: permission denied, open '/data/swagger.yaml'

See also: podman-run(1) - section "Labeling Volume Mounts".